# CI workflow for Quartex NuGet packages
name: Build and publish NuGet package

# Define triggers for when the workflow will run
on:
  push:
    branches: 
      - 'main'

  # Allows manual triggering
  workflow_dispatch:

jobs:

  nuget:
    uses: amdigital-co-uk/quartex-workflows/.github/workflows/nuget.yml@v11
    with:
      PKG_SRC: https://nuget.pkg.github.com/amdigital-co-uk/index.json
      PROJECTS: "Flagsmith.FlagsmithClient"
      SKIP_DUPLICATE: true
    secrets:
      PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
