name: Secrets Check

on:
  push:

jobs:
  check:
    name: Secrets Check
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Check for presence of AWS Access Keys
      - name: Check for AWS Access Keys
        run: |
          echo "Checking for AWS Access Keys committed to source control...."
          grep -R "AKIA[A-z0-9]\{8,\}" | grep -v EXAMPLE > keys.txt || true
          KEYS=$(wc -l keys.txt | cut -d' ' -f1)
          if [ $KEYS -gt 0 ]
          then
            echo "Found AWS Access Keys committed to repository."
            echo "NOTE: Please rotate the affected AWS Keys ASAP!"
            echo "Find and remove these from the following files"
            cat keys.txt | cut -d: -f1
            exit 1
          else
            echo "Good news - no AWS Access Keys found."
            exit 0
          fi
        
      
