# Run unit tests
name: Run Unit Tests

env:
    RUN_TESTS: false # Set to false if repository contains no Unit Tests
    BRANCH_THRESHOLD: 0

# Run when an engineer pushes code to a work branch
on:
  push:
    branches:
      - 'work**'
    paths-ignore:
      - '*.md'
      - '.github/workflows/*'

  # Allows manual triggering
  workflow_dispatch:

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Login to GitHub packages
      - name: Login to GitHub packages
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/amdigital-co-uk/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.PKG_TOKEN}}
    
      # Run Unit Tests
      - name: Run Unit Tests
        if: ${{ env.RUN_TESTS == 'true' }}
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Install code coverage tool
        if: ${{ env.RUN_TESTS == 'true' }}
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
        
      - name: Run report generation
        if: ${{ env.RUN_TESTS == 'true' }}
        run: reportgenerator -reports:$GITHUB_WORKSPACE/*/TestResults/*/coverage.cobertura.xml -targetdir:$RUNNER_TEMP/coverlet/reports -reporttypes:"cobertura"

      - name: Check Branch Coverage
        if: ${{ env.RUN_TESTS == 'true' }}
        id: coverage
        uses: amdigital-co-uk/code-coverage-action@v1.0
        with:
          path: ${{ runner.temp }}/coverlet/reports/Cobertura.xml
          branch_minimum_threshold: ${{ env.BRANCH_THRESHOLD }}


